#!/bin/sh

host=$1
if [ -z "$host" ]; then
	echo "Missing postgres host."
	exit 1
fi

PGPASSWORD=ee414956fe34947659917caa94e83d77
export PGPASSWORD

for i in `seq 1 30`
do
	psql -h $host unifield -q -c 'select 1;' > /dev/null
	if [ $? = 0 ]; then
		# ok
		exit 0
	fi
	echo "Postgres not started. Sleeping."
	sleep 2
done

echo "Timed out waiting for Postgres."
exit 1
