version: '2'

services:
  uf-web:
    image: unifield/web:6.0
    ports:
     - "8061:8061"
    links:
     - uf-server
  uf-server:
    image: unifield/server:6.0
    ports:
     - "8069:8069"
     - "8070:8070"
    links:
     - db
    volumes:
     - ./uf-server:/uf-server
  db:
    image: postgres:9.6.3
    environment:
     - "POSTGRES_PASSWORD=ee414956fe34947659917caa94e83d77"
     - "POSTGRES_USER=unifield"
    volumes:
     - ./postgres-data:/var/lib/postgresql
