FROM python:2.7

RUN	apt-get update && \
	apt-get install -y --no-install-recommends \
		postgresql-client-common \
		postgresql-client \
		net-tools \
		p7zip-full \
	&& apt-get clean

ADD unifield/server /opt/unifield/server
ADD ./wait-postgres-start /opt/unifield/server/bin
ADD ./dot-ufload /home/unifield/.ufload
RUN groupadd -r unifield && useradd -r -g unifield unifield && \
	chown -R unifield:unifield /opt/unifield && \
	pip install --no-cache-dir /opt/unifield/server ufload

USER unifield
CMD /opt/unifield/server/bin/wait-postgres-start db && \
	PYTHONPATH=/opt/unifield/server/bin:/opt/unifield/server/bin/addons python -c 'import updater, osv; from sync_client.sync_client import get_hardware_id; print get_hardware_id()' | tail -1 > /opt/unifield/hwid.txt && \
	/opt/unifield/server/bin/openerp-server.py --db_host=db \
		--db_password=ee414956fe34947659917caa94e83d77 \
		--netrpc-interface=0.0.0.0
